name: Sietra Merkezi Dagitim Pipeline
   on:
     push:
       branches:
         - main

   jobs:
     deploy:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout Repository
           uses: actions/checkout@v4

         - name: Deploy to Firebase Hosting
           uses: FirebaseExtended/action-hosting-deploy@v0
           with:
             repoToken: '${{ secrets.GITHUB_TOKEN }}'
             firebaseServiceAccount: '${{ secrets.SIETRA_MERKEZI_DAGITIM_PIPELINE }}'
             channelId: live
             projectId: sietra-merkezi-dagitim
